'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def main():
	FibonacciNumber1 = 1
	FibonacciNumber2 = 1
	SumOfFibonacciNumbers= 0 #Up to four million
	while (FibonacciNumber1 < 4000000 or FibonacciNumber2 < 4000000):
		FibonacciNumber1 = FibonacciNumber1 + FibonacciNumber2
		if ((FibonacciNumber1%2) == 0):
			SumOfFibonacciNumbers = SumOfFibonacciNumbers + FibonacciNumber1
		if (FibonacciNumber1 > 4000000 or FibonacciNumber2 > 4000000):
			break
		FibonacciNumber2 = FibonacciNumber1 + FibonacciNumber2
		if ((FibonacciNumber2%2) == 0):
			SumOfFibonacciNumbers = SumOfFibonacciNumbers + FibonacciNumber2
	print(SumOfFibonacciNumbers)
#call to main
main()